apiVersion: apps/v1
kind: Deployment
metadata:
  name: stratus
spec:
  selector:
    matchLabels:
      app: stratus
  replicas: 4
  template:
    metadata:
      labels:
        app: stratus
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app 
                operator: In
                values:
                -  stratus
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: stratus-container
        image: k8s.gcr.io/pause:2.0
        resources:
          requests:
            cpu: "200m"
            memory: "900M"
