apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
spec:
  selector:
    matchLabels:
      app: proxy-server
  replicas: 3
  template:
    metadata:
      labels:
        app: proxy-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - proxy-server
            topologyKey: "kubernetes.io/hostname"
      schedulerName: boreas-scheduler
      containers:
        - name: nginx
          image: "nginx:1.14.1-alpine"
          resources:
            requests:
              cpu: "250m"
              memory: "128M"
