apiVersion: v1
kind: Pod
metadata:
  name: annotation-boreas-scheduler
  labels:
    name: multischeduler-example
spec:
  schedulerName: boreas-scheduler
  containers:
  - name: pod-with-second-annotation-container
    image: k8s.gcr.io/pause:2.0
    resources:
      requests:
        cpu: '0.1'
        memory: "128M"
