apiVersion: v1
kind: ServiceAccount
metadata:
  name: boreas-scheduler
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: boreas-scheduler-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: boreas-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: boreas-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        version: second
    spec:
      serviceAccount: boreas-scheduler
      containers:
      - name: boreas-scheduler
        image: localhost:5000/boreas-scheduler:local
        livenessProbe:
          httpGet:
            path: /health
            port: 10251
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 10251
        resources:
          requests:
            cpu: '0.1'
        securityContext:
          privileged: false
        volumeMounts: []
      - name: zephyrus2
        image: jacopomauro/zephyrus2:v2.0.2
        livenessProbe:
          httpGet:
            path: /health
            port: 9001
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 9001
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      hostNetwork: false
      hostPID: false
      volumes: []
