apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
spec:
  selector:
    matchLabels:
      app: cache
  replicas: 3
  template:
    metadata:
      labels:
        app: cache
    spec:
      schedulerName: boreas-scheduler
      containers:
      - name: cache-container
        image: k8s.gcr.io/pause:2.0
        resources:
          requests:
            cpu: "200m"
            memory: "400M"
