apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple
spec:
  selector:
    matchLabels:
      app: simple
  replicas: 40
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - name: simple-container
        image: k8s.gcr.io/pause
        resources:
          requests:
            cpu: "475m"
            memory: "2040M"
