apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple
spec:
  selector:
    matchLabels:
      app: simple
  replicas: 20
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - name: simple-container
        image: k8s.gcr.io/pause:2.0
        resources:
          requests:
            cpu: "180m"
            memory: "750M"
