apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      schedulerName: boreas-scheduler
      containers:
      - name: backend-container
        image: k8s.gcr.io/pause:2.0
        resources:
          requests:
            cpu: "300m"
            memory: "500M"
