apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 2
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy-container
        image: k8s.gcr.io/pause:2.0
        resources:
          requests:
            cpu: "300m"
            memory: "600M"
