apiVersion: apps/v1
kind: Deployment
metadata:
  name: cirrus
spec:
  selector:
    matchLabels:
      app: cirrus
  replicas: 2
  template:
    metadata:
      labels:
        app: cirrus
    spec:
      schedulerName: boreas-scheduler
      containers:
      - name: cirrus-container
        image: k8s.gcr.io/pause:2.0
        resources:
          requests:
            cpu: "200m"
            memory: "900M"
